services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/store
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mongo-data:
